name: igcheatmap - On external trigger

# Controls when the action will run. Triggers the workflow on repository_dispatch and filters by type of event (i.e. `event_type`)
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: false

env:
  project_id: igcheatmap
  tilehut_server_image_name: "eu.gcr.io/igcheatmap/thermalmap-tilehut-server:latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tilehut-server 
        uses: actions/checkout@v3
        
      # TODO:

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.tilehut_server_image_name }}
          
      - name: Push to Container registry
        uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY_IGCHEATMAP }}
          registry: eu.gcr.io
          project_id: ${{ env.project_id}}
          image_name: thermalmap-tilehut-server
          image_tag: latest
          push_only: true
          
  deploy-to-google-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY_igcheatmap }}'

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        image: env.tilehut_server_image_name
        service: 'thermalmap-tilehut-server'
        region: 'europe-west9'
